Of ... at expression
avast/yaramod pull request #252
Opened 2023-07-24 14:40 UTC by vojone

Added support for `... of ... at ...` expression, that is supported in YARA 4.3.

2023-07-24 17:11 UTC, metthal requested changes
Since we have `of ... in ...` and `of ... at ...` in YARA now and it's hard to distinguish between those 2 when using function overloads, you decided to introduce `ofAt/of_at`. I'm not against it, but I would prefer if we stop using function overloading for `of ... in ...` and instead name it all explicitly, so in the end, we would have `of`, `ofInRange` and `ofAt`. I think that's better than having `of` for both `of ...` and `of ... in ...` and then `ofAt` for `of ... at ...`.

2023-07-25 08:55 UTC, vojone commented
Due to review, I renamed the second overload of `of` to `OfInRange`/`of_in_range`. It should be more clear now. I was originally afraid of that changing the name of the method would break existing applications using yaramod.

2023-07-25 09:27 UTC, metthal requested changes

2023-07-25 09:27 UTC, metthal commented on src/python/typings/__init__.pyi
>  def of(arg0: YaraExpressionBuilder, arg1: YaraExpressionBuilder, arg2: YaraExpressionBuilder) -> YaraExpressionBuilder: ...
This line needs to be changed too.

2023-07-31 12:48 UTC, metthal approved these changes

2023-07-31 12:48 UTC, merged